// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Qui\xE9n soy",
  description: "Devuelve el perfil del usuario autenticado (nombre, email, roles y plaza).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY;
    const client = createClient(url, key, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: rolesData }] = await Promise.all([
      client.from("profiles").select("full_name,email,phone,plaza_id,approval_status").eq("user_id", userId).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? profile?.email ?? null,
      full_name: profile?.full_name ?? null,
      phone: profile?.phone ?? null,
      plaza_id: profile?.plaza_id ?? null,
      approval_status: profile?.approval_status ?? null,
      roles: (rolesData ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-companies.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var search_companies_default = defineTool2({
  name: "search_companies",
  title: "Buscar empresas",
  description: "Busca empresas (clientes/prospectos) en el directorio por nombre o raz\xF3n social. Devuelve hasta 20 coincidencias que el usuario autenticado tenga permitido ver.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Texto a buscar en el nombre o raz\xF3n social."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de resultados (por defecto 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const client = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const max = limit ?? 20;
    const q = query.replace(/[%,]/g, " ").trim();
    const { data, error } = await client.from("companies").select("id,name,razon_social,industry,phone,email,website").or(`name.ilike.%${q}%,razon_social.ilike.%${q}%`).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, results: rows }
    };
  }
});

// src/lib/mcp/tools/list-overdue-invoices.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_overdue_invoices_default = defineTool3({
  name: "list_overdue_invoices",
  title: "Listar facturas vencidas",
  description: "Lista las facturas con estatus distinto a 'pagada' y saldo pendiente, para las empresas visibles por el usuario autenticado. Devuelve hasta 50 registros ordenados por fecha de vencimiento.",
  inputSchema: {
    company_id: z2.string().uuid().optional().describe("Filtrar por una empresa espec\xEDfica."),
    only_overdue: z2.boolean().optional().describe("Si es true, solo devuelve facturas ya vencidas (fecha_vencimiento < hoy)."),
    limit: z2.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (por defecto 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id, only_overdue, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const client = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = client.from("documents").select("id,numero,fecha,fecha_vencimiento,total,saldo_pendiente_cobranza,monto_pagado,estatus_factura,company_id,companies(name)").eq("tipo_documento", "factura").neq("estatus_factura", "pagada").order("fecha_vencimiento", { ascending: true }).limit(limit ?? 50);
    if (company_id) q = q.eq("company_id", company_id);
    if (only_overdue) q = q.lt("fecha_vencimiento", (/* @__PURE__ */ new Date()).toISOString().slice(0, 10));
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, invoices: rows }
    };
  }
});

// src/lib/mcp/tools/list-pending-activities.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_pending_activities_default = defineTool4({
  name: "list_pending_activities",
  title: "Listar actividades y tareas pendientes",
  description: "Devuelve las actividades/tareas CRM pendientes que el usuario autenticado puede ver (seg\xFAn sus permisos).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (por defecto 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const client = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await client.from("crm_tasks").select("id,title,description,due_date,completed,priority,task_type,company_id,contact_id,companies(name)").eq("completed", false).order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { count: rows.length, tasks: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fnqeicdqblkhfpyboxre";
var mcp_default = defineMcp({
  name: "lumaggs-portal-mcp",
  title: "Portal Lumaggs / Galsa",
  version: "0.1.0",
  instructions: "Herramientas del Portal Lumaggs/Galsa. Cada llamada act\xFAa como el usuario autenticado y respeta sus permisos (RLS). Usa `whoami` para verificar sesi\xF3n, `search_companies` para buscar empresas, `list_overdue_invoices` para cartera vencida y `list_pending_activities` para las tareas pendientes del CRM.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, search_companies_default, list_overdue_invoices_default, list_pending_activities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
