INSERT INTO public.template_placeholders (key, label, description, source_table, source_field, applies_to, sort_order, example_value) VALUES
('{registrado_por}',      'Registrado por',       'Nombre del usuario que registró el pago',          'profiles',          'full_name',          'email', 200, 'María González'),
('{monto_pago}',          'Monto del pago',        'Monto total del pago registrado en MXN',           'cobranza_pagos',    'monto_total',        'email', 210, '$12,500.00'),
('{fecha_pago}',          'Fecha de pago',         'Fecha en que se registró el pago',                 'cobranza_pagos',    'fecha_pago',         'email', 220, '05/05/2026'),
('{tipo_pago}',           'Tipo de pago',          'Forma de pago: transferencia, cheque, efectivo',   'cobranza_pagos',    'tipo_pago',          'email', 230, 'Transferencia'),
('{referencia_pago}',     'Referencia de pago',    'Número de referencia o folio bancario',            'cobranza_pagos',    'referencia_pago',    'email', 240, 'REF-789456'),
('{banco}',               'Banco',                 'Banco emisor del pago',                            'cobranza_pagos',    'banco',              'email', 250, 'BBVA'),
('{observaciones}',       'Observaciones',         'Notas u observaciones adicionales del pago',       'cobranza_pagos',    'observaciones',      'email', 260, 'Pago parcial de factura TIJ2489'),
('{monto_aplicado}',      'Monto aplicado',        'Monto del pago ya aplicado a facturas',            'cobranza_pagos',    'monto_aplicado',     'email', 270, '$10,000.00'),
('{monto_disponible}',    'Monto disponible',      'Saldo disponible del pago no aplicado aún',        'cobranza_pagos',    'monto_disponible',   'email', 280, '$2,500.00'),
('{numero_factura}',      'Número de factura',     'Folio o número de la factura',                     'documentos',        'numero_factura',     'ambos', 290, 'TIJ2489'),
('{nombre_empresa_vendedora}', 'Empresa vendedora', 'Razón social de la empresa que vende (Lumaggs / Galsa)', 'documentos', 'empresa_vendedora', 'ambos', 300, 'Lumaggs SA de CV'),
('{rfc_cliente}',         'RFC del cliente',       'RFC fiscal de la empresa cliente',                 'companies',         'rfc',                'email', 310, 'TAB123456XYZ'),
('{telefono_ejecutivo}',  'Teléfono del ejecutivo','Teléfono del ejecutivo de venta asignado',         'profiles',          'phone',              'ambos', 320, '+52 664 123 4567'),
('{correo_ejecutivo}',    'Correo del ejecutivo',  'Email del ejecutivo de venta asignado',            'profiles',          'email',              'email', 330, 'ejecutivo@empresa.com'),
('{direccion_entrega_calle}',   'Calle (entrega)',        'Calle y número de la dirección de entrega',     'direcciones_empresa', 'calle',          'email', 400, 'Av. Reforma 123'),
('{direccion_entrega_colonia}', 'Colonia (entrega)',      'Colonia de la dirección de entrega',            'direcciones_empresa', 'colonia',        'email', 410, 'Centro'),
('{direccion_entrega_ciudad}',  'Ciudad (entrega)',       'Ciudad de la dirección de entrega',             'direcciones_empresa', 'ciudad',         'email', 420, 'Tijuana'),
('{direccion_entrega_cp}',      'CP (entrega)',           'Código postal de la dirección de entrega',      'direcciones_empresa', 'codigo_postal',  'email', 430, '22000'),
('{direccion_entrega_estado}',  'Estado (entrega)',       'Estado de la dirección de entrega',             'direcciones_empresa', 'estado',         'email', 440, 'Baja California'),
('{direccion_entrega_completa}','Dirección completa',     'Dirección de entrega formateada en una línea',  'direcciones_empresa', NULL,             'ambos', 450, 'Av. Reforma 123, Centro, Tijuana, BC 22000'),
('{instrucciones_entrega}',     'Instrucciones de entrega','Indicaciones especiales para la entrega',     'documentos',          'notas_entrega',  'email', 460, 'Entregar en bodega trasera, preguntar por Carlos'),
('{fecha_entrega_programada}',  'Fecha de entrega programada','Fecha programada para la entrega',         'entregas_programadas', 'fecha_entrega', 'ambos', 470, '07/05/2026'),
('{repartidor}',                'Repartidor',             'Nombre del repartidor asignado a la entrega',   'repartidores',        'nombre',         'email', 480, 'Juan Ramírez'),
('{url_comprobante}',     'URL comprobante de pago', 'Enlace al archivo del comprobante de pago subido','cobranza_pago_archivos','url_archivo',   'email', 500, 'https://...'),
('{url_factura_pdf}',     'URL factura PDF',         'Enlace al PDF de la factura',                     'documento_archivos_firmados','url_archivo','email', 510, 'https://...'),
('{url_documento}',       'URL del documento',       'Enlace directo al documento en el sistema',        'documentos',         NULL,             'email', 520, 'https://app.empresa.com/documentos/123'),
('{archivos_adjuntos}',   'Archivos adjuntos',       'Lista de URLs de archivos adjuntos al documento', 'documento_archivos_firmados',NULL,        'email', 530, 'https://archivo1.pdf, https://archivo2.pdf')
ON CONFLICT (key) DO NOTHING;